/*
 * Copyright 2017, 2024 Precisely. All rights reserved.
 * This document contains unpublished, confidential, and proprietary information of Precisely.
 * No disclosure or use of any portion of the contents of this document may be made without the express written consent of Precisely.
*/

package com.precisely.bigdata.li.spark.app.drivers.seachnearest;

import com.precisely.bigdata.li.spark.app.searchnearest.SearchNearestDriver;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.getRowsSorted;
import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.hasResultsFile;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class SearchNearestDriverTest {
    private static File BASE_DIR;
    private static File OUTPUT_DIR;

    @BeforeAll
    public static void setup() throws IOException {
        BASE_DIR = Files.createTempDirectory(Paths.get("build"), SearchNearestDriverTest.class.getName()).toFile();
        OUTPUT_DIR =  new File(BASE_DIR, "output");
        System.setProperty("spark.master", "local[*]");
        System.setProperty("spark.app.name", "SearchNearestDriverTester");
    }

    @AfterAll
    public static void cleanup() {
        FileUtils.deleteQuietly(BASE_DIR);
    }

    @AfterEach
    public void afterEach() {
        FileUtils.deleteQuietly(OUTPUT_DIR);
    }

    @Test
    public void test_searchNearest_e2e_with_GeoJSON_geometry() throws IOException {
        String pointData = new File("src/test/resources/geometryGeoJson.csv").getAbsolutePath();
        String tabDataPath = new File("src/test/resources/states").getAbsolutePath();

        String[] args = {
                "--input", pointData,
                "--csv", "header=true",
                "--csv", "delimiter=\\t",
                "--table-file-type", "TAB",
                "--table-file-path", tabDataPath,
                "--table-file-name", "STATES.TAB",
                "--geometry-string-type", "GeoJSON",
                "--geometry-column-name", "geometry",
                "--distance", "20",
                "--distance-unit", "km",
                "--max-candidates", "20",
                "--output", OUTPUT_DIR.getAbsolutePath(),
                "--output-fields", "State_Name", "State",
                "--include-empty-search-results",
                "--overwrite"};
        //Executing job
        SearchNearestDriver.main(args);

        assertTrue(hasResultsFile(OUTPUT_DIR), "Output file 'part-00000' not generated by SearchNearestDriver Spark job.");
        List<String> lines = getRowsSorted(OUTPUT_DIR, true);
        assertEquals(14, lines.size());

        assertEquals("lineString\t\"{\\\"coordinates\\\":[[-89.25838794138288,32.41702581572919],[-84.05711292738704,34.892496614402745],[-85.13271613870991,37.75653393300398]],\\\"type\\\":\\\"LineString\\\"}\"\tAlabama\tAL\t0.0", lines.get(0));
        assertEquals("lineString\t\"{\\\"coordinates\\\":[[-89.25838794138288,32.41702581572919],[-84.05711292738704,34.892496614402745],[-85.13271613870991,37.75653393300398]],\\\"type\\\":\\\"LineString\\\"}\"\tGeorgia\tGA\t0.0", lines.get(1));
    }

    @Test
    public void test_searchNearest_e2e_with_WKT_geometry() throws IOException {
        String pointData = new File("src/test/resources/geometryWKT.csv").getAbsolutePath();
        String tabDataPath = new File("src/test/resources/states").getAbsolutePath();

        String[] args = {
                "--input", pointData,
                "--csv", "header=true",
                "--csv", "delimiter=\\t",
                "--table-file-type", "TAB",
                "--table-file-path", tabDataPath,
                "--table-file-name", "STATES.TAB",
                "--geometry-string-type", "WKT",
                "--geometry-column-name", "geometry",
                "--distance", "20",
                "--distance-unit", "km",
                "--max-candidates", "20",
                "--output", OUTPUT_DIR.getAbsolutePath(),
                "--output-fields", "State_Name", "State",
                "--include-empty-search-results",
                "--overwrite"};
        //Executing job
        SearchNearestDriver.main(args);

        assertTrue(hasResultsFile(OUTPUT_DIR), "Output file 'part-00000' not generated by SearchNearestDriver Spark job.");
        List<String> lines = getRowsSorted(OUTPUT_DIR, true);
        assertEquals(14, lines.size());

        assertEquals("lineString\tLINESTRING (-89.25838794138288 32.41702581572919, -84.05711292738704 34.892496614402745, -85.13271613870991 37.75653393300398)\tAlabama\tAL\t0.0", lines.get(0));
        assertEquals("lineString\tLINESTRING (-89.25838794138288 32.41702581572919, -84.05711292738704 34.892496614402745, -85.13271613870991 37.75653393300398)\tGeorgia\tGA\t0.0", lines.get(1));
    }

    /*@Test
    public void test_searchNearest_e2e_with_WKB_geometry() throws IOException {
        String pointData = new File("src/test/resources/geometryWKB.csv").getAbsolutePath();
        String tabDataPath = new File("src/test/resources/states").getAbsolutePath();

        String[] args = {
                "--input", pointData,
                "--csv", "header=true",
                "--csv", "delimiter=\\t",
                "--table-file-type", "TAB",
                "--table-file-path", tabDataPath,
                "--table-file-name", "STATES.TAB",
                "--geometry-string-type", "WKB",
                "--geometry-column-name", "geometry",
                "--distance", "20",
                "--distance-unit", "km",
                "--max-candidates", "20",
                "--output", OUTPUT_DIR.getAbsolutePath(),
                "--output-fields", "State_Name", "State",
                "--include-empty-search-results",
                "--overwrite"};
        //Executing job
        SearchNearestDriver.main(args);

        assertTrue("Output file 'part-00000' not generated by SearchNearestDriver Spark job.", hasResultsFile(OUTPUT_DIR));
        List<String> lines = getRowsSorted(OUTPUT_DIR, true);
        assertEquals(14, lines.size());

        assertEquals("lineString\tLINESTRING (-89.25838794138288 32.41702581572919, -84.05711292738704 34.892496614402745, -85.13271613870991 37.75653393300398)\tAlabama\tAL\t0.0", lines.get(0));
        assertEquals("lineString\tLINESTRING (-89.25838794138288 32.41702581572919, -84.05711292738704 34.892496614402745, -85.13271613870991 37.75653393300398)\tGeorgia\tGA\t0.0", lines.get(1));
    }*/
}
