/*
 * Copyright 2017, 2024 Precisely. All rights reserved.
 * This document contains unpublished, confidential, and proprietary information of Precisely.
 * No disclosure or use of any portion of the contents of this document may be made without the express written consent of Precisely.
 */

package com.precisely.bigdata.li.spark.app.drivers.joinbydistance;

import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.getRowsSorted;
import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.hasResultsFile;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public final class JoinByDistanceTest {
    private static File BASE_DIR;
    private static File OUTPUT_DIR;

    @BeforeAll
    public static void setup() throws IOException {
        BASE_DIR = Files.createTempDirectory(Paths.get("build"), JoinByDistanceTest.class.getName()).toFile();
        OUTPUT_DIR = new File(BASE_DIR, "output");
        System.setProperty("spark.master", "local[*]");
        System.setProperty("spark.app.name", "JoinByDistanceDriverTest");
    }

    @AfterAll
    public static void cleanup() {
        FileUtils.deleteQuietly(BASE_DIR);
    }

    @AfterEach
    public void afterEach() {
        FileUtils.deleteQuietly(OUTPUT_DIR);
    }

    @Test
    public void test_PointInPolygon_e2e() throws IOException {
        String[] args = getArgs();
        JoinByDistanceDriver.main(args);
        assertTrue(hasResultsFile(OUTPUT_DIR), "Output file 'part-00000' not generated by JoinByDistanceDriver Spark job.");
        List<String> lines = getRowsSorted(OUTPUT_DIR, true);
        assertEquals(15, lines.size());
    }

    private static String[] getArgs() {
        String df1 = new File("src/test/resources/jbd1.csv").getAbsolutePath();
        String df2 = new File("src/test/resources/jbd2.csv").getAbsolutePath();

        return new String[]{
                "--input1", df1,
                "--input2", df2,
                "--csv", "header=true",
                "--csv1", "header=true",
                "--csv1", "inferSchema=true",
                "--csv2", "header=true",
                "--csv2", "inferSchema=true",
                "--search-radius", "5.0",
                "--distance-unit", "mi",
                "--longitude1", "Longitude",
                "--longitude2", "Lon",
                "--latitude1", "Latitude",
                "--latitude2", "Lat",
                "--geo-hash-precision", "7",
                "--distance-column-name", "outputDistance",
                "--limit-matches", "5",
                "--limit-method", "RowNumber",
                "--output", OUTPUT_DIR.getAbsolutePath(),
                "--overwrite"};
    }
}
