/*
 * Copyright 2017, 2024 Precisely. All rights reserved.
 * This document contains unpublished, confidential, and proprietary information of Precisely.
 * No disclosure or use of any portion of the contents of this document may be made without the express written consent of Precisely.
 */
package com.precisely.bigdata.li.spark.app.drivers.hexgen;

import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.getRowsSorted;
import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.hasResultsFile;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class HexgenDriverTest {
    private static File BASE_DIR;
    private static File OUTPUT_DIR;

    @BeforeAll
    public static void setup() throws IOException {
        BASE_DIR = Files.createTempDirectory(Paths.get("build"), HexgenDriverTest.class.getName()).toFile();
        OUTPUT_DIR = new File(BASE_DIR, "output");
        System.setProperty("spark.master", "local[*]");
        System.setProperty("spark.app.name", "HexGenDriverTest");
    }

    @AfterAll
    public static void cleanup() {
        FileUtils.deleteQuietly(BASE_DIR);
    }

    @AfterEach
    public void afterEach() {
        FileUtils.deleteQuietly(OUTPUT_DIR);
    }

    @Test
    public void test_hexgenApp_e2e() throws Exception {
        String[] args = {
                "--min-longitude", "-73.728200",
                "--min-latitude", "40.979800",
                "--max-longitude", "-71.787480",
                "--max-latitude", "42.050496",
                "--hex-level", "3",
                "--container-level", "2",
                "--number-of-partitions", "5",
                "--max-number-of-rows", "5",
                "--csv", "header=true",
                "--output", OUTPUT_DIR.getAbsolutePath()
        };
        //Executing job
        HexGenDriver.main(args);

        assertTrue(hasResultsFile(OUTPUT_DIR), "Output file 'part-00000' not generated by HexGenDriver Spark job.");
        List<String> lines = getRowsSorted(OUTPUT_DIR, true);
        assertEquals(30, lines.size());

        assertEquals("PF380,\"POLYGON ((-73.8271604938 40.2585722649, -73.5802469136 40.5841525254, -73.0864197531 40.5841525254, -72.8395061728 40.2585722649, -73.0864197531 39.931417739, -73.5802469136 39.931417739, -73.8271604938 40.2585722649))\",-73.33333333333334,40.257785132176366", lines.get(0));
        assertEquals("PF381,\"POLYGON ((-74.5679012346 40.5841525254, -74.3209876543 40.9081556333, -73.8271604938 40.9081556333, -73.5802469136 40.5841525254, -73.8271604938 40.2585722649, -74.3209876543 40.2585722649, -74.5679012346 40.5841525254))\",-74.07407407407408,40.583363949126685", lines.get(1));
        assertEquals("PF3810,\"POLYGON ((-74.2386831276 40.3672740838, -74.1563786008 40.4758008729, -73.9917695473 40.4758008729, -73.9094650206 40.3672740838, -73.9917695473 40.2585722649, -74.1563786008 40.2585722649, -74.2386831276 40.3672740838))\",-74.07407407407408,40.367186568931245", lines.get(2));
    }
}
