/*
 * Copyright 2017, 2024 Precisely. All rights reserved.
 * This document contains unpublished, confidential, and proprietary information of Precisely.
 * No disclosure or use of any portion of the contents of this document may be made without the express written consent of Precisely.
*/

package com.precisely.bigdata.li.spark.app.drivers.pointinpolygon;

import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.getRowsSorted;
import static com.precisely.bigdata.li.spark.app.drivers.utils.TestUtils.hasResultsFile;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public final class PointInPolygonDriverTest {
    private static File BASE_DIR;
    private static File OUTPUT_DIR;

    @BeforeAll
    public static void setup() throws IOException {
        BASE_DIR = Files.createTempDirectory(Paths.get("build"), PointInPolygonDriverTest.class.getName()).toFile();
        OUTPUT_DIR =  new File(BASE_DIR, "output");
        System.setProperty("spark.master", "local[*]");
        System.setProperty("spark.app.name", "PointInPolygonDriverTest");
    }

    @AfterAll
    public static void cleanup() {
        FileUtils.deleteQuietly(BASE_DIR);
    }

    @AfterEach
    public void afterEach() {
        FileUtils.deleteQuietly(OUTPUT_DIR);
    }

    @Test
    public void test_PointInPolygon_e2e() throws IOException {
        String pointData = new File("src/test/resources/addressFabric50.csv").getAbsolutePath();
        String tabDataPath = new File("src/test/resources/uszips").getAbsolutePath();

        String[] args = {
                "--input", pointData,
                "--csv", "header=true",
                "--table-file-type", "TAB",
                "--table-file-path", tabDataPath,
                "--table-file-name", "USZIPBDY.TAB",
                "--latitude-column-name", "LAT",
                "--longitude-column-name", "LON",
                "--output", OUTPUT_DIR.getAbsolutePath(),
                "--output-fields", "ZIP", "Name",
                "--include-empty-search-results",
                "--overwrite"};
        //Executing job
        PointInPolygonDriver.main(args);

        assertTrue(hasResultsFile(OUTPUT_DIR), "Output file 'part-00000' not generated by PointInPolygonDriver Spark job.");
        List<String> lines = getRowsSorted(OUTPUT_DIR, true);
        assertEquals(50, lines.size());
        assertEquals("P0000GL4117Q,288,KRUMKILL RD,,,SLINGERLANDS,NY,12159,P02,3.6001E+14,42.659748,-73.838572,,R,12159,Slingerlands", lines.get(0));
        assertEquals("P0000GL4117R,285,KRUMKILL RD,,,Lucknow,UP,225001,P02,3.6001E+14,19.26730767,72.94822527,,R,,", lines.get(1));
    }
}
